### ISSUE TITLE
Walking

### ISSUE THREAD

**Issue by suhr** [Ralith/hypermine#127]
Looking around is already cool, but even more cool would being able to *walk* on this terrain.

Depends on https://github.com/Ralith/hypermine/issues/34 I guess.

**Comment by dranorter** [comment]
The issue with walking is gravity. Hyperblock recently decided to use a very Escher-like gravity: https://www.youtube.com/watch?v=NzK0MCwgLE8 but other solutions would be possible; nothing is perfectly intuitive.

**Comment by Ralith** [comment]
To the contrary, the issue is collision detection. It's easy enough to come up with a consistent rule for gravity, but that's no use if you just fall forever.
