### ISSUE TITLE
Crashes entire OS

### ISSUE THREAD

**Issue by dranorter** [Ralith/hypermine#156]
I started up Hypermine for the first time and looked around a bit. After just a couple minutes both my screens stopped receiving output from my video card. The computer didn't appear to shut down; I had to do a hard shutdown and restart. I don't see any log files so I'm not sure how to give more information.

I'm going to try leaving some audio playing in the background so that I at least know whether that gets stopped by the crash.

**Comment by dranorter** [comment]
Sadly I haven't reproduced the behavior yet.

**Comment by Ralith** [comment]
System-wide failures are the responsibility of your drivers and/or hardware.

**Comment by dranorter** [comment]
OK, fair point.
