### ISSUE TITLE
python3 not recognized as "python"

### ISSUE THREAD

**Issue by DimpyRed** [Ralith/hypermine#177]
With my new computer I had been getting an error in the build process that "python" was not a recognized command
```
thread 'main' panicked at '

 couldn't find required command: "python"

  '
```
I was able to fix it by installing the package python-is-python3, but it would be incredibly helpful for other users if they didn't need to do so, or if the troubleshooting message was more informative.

**Comment by Ralith** [comment]
This is probably an issue for upstream https://github.com/google/shaderc-rs.
