### ISSUE TITLE
Label dodeca sides

### ISSUE THREAD

**Issue by stingpie** [Ralith/hypermine#196]
I'm trying to mess around with the code a little bit, and trying to implement my own inter-chunk generation similar to roads, and I'm noticing a pretty crucial part of it is trying to figure out which side of the dodeca is up, which sides correspond to horizontal, and which sides correspond to down. (please note I'm looking at this code from an outside perspective, so if this is a dumb question, please forgive me. )

looking on worldgen.rs, adjacent chunks of the road object are labeled based on the dodeca.rs class. I want to try my hand at building a tree, so I want to know how to extend an object similar to road into 2 dimensions. The issue is I don't know how the sides in dodeca correspond to directions in the actual world.

**Comment by Ralith** [comment]
There is no direct correspondence; orientations of dodecahedrons in the world vary depending on their location. For example, two neighboring dodecahedrons are reflections of eachother, assigning the same label to a shared face that points in opposite directions wrt. each dodecahedron's center in world space. Determining geometric relationships in hyperbolic space requires computing in hyperbolic geometry, and special care is required for relationships that might span multiple dodecahedra as numerical error accumulates very rapidly.

**Comment by stingpie** [comment]
I need to at least know the relative position of each face. Is face A adjacent to face B? can you at least draw an mspaint diagram of it?

**Comment by Ralith** [comment]
> Is face A adjacent to face B?

See `dodeca::Side::adjacent_to`.

**Comment by patowen** [comment]
This may be subject to change, but currently (as of today), the faces are arranged as follows:

Side A is adjacent to 5 other sides, which, in order, are B, E, I, D, C. In the root node, this order is counterclockwise when viewed from the outside of the dodecahedron (unless I messed up). Adjacent nodes are mirrored from each other, so the order I gave will be clockwise for some dodecahedra.

This covers the 6 faces of one half of the dodecahedron. For the other half, you can use the following ordered pairs of faces that oppose each other: (A, J), (B, K), (C, L), (D, G), (E, H), and (F, I).
