### ISSUE TITLE
Surface extraction can produce extra surfaces with a risk of z-fighting

### ISSUE THREAD

**Issue by patowen** [Ralith/hypermine#330]
If a voxel in the chunk's margin is solid but is next to a void voxel in the chunk's interior, the surface extraction logic will produce a surface on a face of the chunk that can be viewed from the inside. This is redundant with the adjacent chunk, causing the same voxel face to be rendered twice, which results in overdraw and could result in z-fighting (for instance, if the textures are oriented differently).

For potential surfaces that span a margin voxel and an interior voxel, the surface should only be rendered ~if the interior voxel is solid and the margin voxel is void~ if the margin voxel is solid and the interior voxel is void, not vice versa. (See comment thread below on why this edit was made)

Fixing this would also slightly reduce the worst-case number of surfaces when the dimension is even to `3*d^3` (but still `3*(d^3+d^2)` when odd). For simplicity of reasoning, though, it may not be worth taking advantage of this.

This issue won't be apparent until #41 is resolved,

**Comment by patowen** [comment]
I'm actually somewhat curious about this issue. Just after filing #379, I'm wondering if I got it backwards. As in, perhaps the surface should only be rendered if the margin voxel is solid and the interior voxel is void, not vice versa.

My reasoning here is that, if everything goes well, it might take less work to get accurate ambient occlusion. With the original scheme, edge and corner margins both affect ambient occlusion, but since 20 chunks can meet at a single corner, corner margins can be very difficult to maintain, especially efficiently. However, with this reversal, I believe (but have not confirmed) that corner margins would no longer play any role at all, and we would only have to worry about the somewhat-tricky edge margins.

**Comment by Ralith** [comment]
> perhaps the surface should only be rendered if the margin voxel is solid and the interior voxel is void, not vice versa.

Makes sense to me! I wouldn't stress making AO perfect, since it's just an expedient hack, but this seems like a free improvement.

> This would have an effect on texture orientation, which might be confusing to the player.

Meh, so long as there's a solid surface I don't really care. The whole surface extraction paradigm is subject to change, we shouldn't micro-optimize the aesthetics of the status quo too hard.

> we'll need to remember that side-margins need to have the correct material (and not just be correctly void or non-void like edge margins can be)

Aren't we achieving that anyway?

**Comment by patowen** [comment]
> Makes sense to me! I wouldn't stress making AO perfect, since it's just an expedient hack, but this seems like a free improvement.

> Meh, so long as there's a solid surface I don't really care. The whole surface extraction paradigm is subject to change, we shouldn't micro-optimize the aesthetics of the status quo too hard.

Good to know that you're on board with this idea! I'll go ahead an apply it my current branch since it seems more likely than not to be our final state.

> Aren't we achieving that anyway?

Oh yeah, we are. That was almost a note-to-self, because I has considered other designs before, such as always using dirt or void, just to make it easier to be consistent with edge margins, for example. This certainly isn't a downside to this approach.

**Comment by patowen** [comment]
It does look like this has immediate benefits as well, mainly because, although edge margins are still needed, they're needed in fewer places.

Before:
![image](https://github.com/Ralith/hypermine/assets/5403380/2fafc84c-a546-4829-8d9c-f71e2ae1c789)

After:
![image](https://github.com/Ralith/hypermine/assets/5403380/788d1808-966b-4532-aecd-c70a484cf827)
