### ISSUE TITLE
Models load failed

### ISSUE THREAD

**Issue by sharma-shray** [Ralith/hypermine#366]
Hi, error during build

 ERROR character model load failed: /../ character.glb: not glTF magic
 ERROR voxel materials load failed: /../materials/00001_dirt.png: Invalid PNG signature.
 
 these files are in the folders

**Comment by juh9870** [comment]
Looks like you forgot to do `git lfs pull`

**Comment by sharma-shray** [comment]
> Looks like you forgot to do `git lfs pull`

Yes, thank you. It would be great to add this mention in README.md

**Comment by juh9870** [comment]
It is mentioned in build instructions on wiki, which is the first thing linked in README
https://github.com/Ralith/hypermine/wiki
