### ISSUE TITLE
Short-circuit terrain gen for empty/solid chunks

### ISSUE THREAD

**Issue by Ralith** [Ralith/hypermine#40]
We're spending a lot of CPU time deciding that every single voxel of every single empty chunk is indeed empty. We should be able to use the values of the max elevation field at the vertices of a chunk, combined with knowledge of the shape of the distance field to the ground plane, to efficiently determine that a chunk has no/exclusively solid voxels and skip it.

Care will be necessary when optimizing solid chunks, as they must only be short-circuited if their margins are also solid. However, we can ignore (i.e. assume solid) margins facing nodes that have not yet been constructed, because a chunk cannot possibly be observed from that direction; such faces would always be backface-culled by a camera located within the graph.

**Comment by Ralith** [comment]
@MagmaMcFry do you have a method to compute the minimum and maximum distance field values within a chunk? I think that's most of what we need here.

**Comment by MagmaMcFry** [comment]
It should be sufficient to compute the field values at the corners and add a constant margin.

**Comment by Ralith** [comment]
I'm still blocked hard on determining what exactly that margin is. Can you elaborate?

**Comment by Ralith** [comment]
Mostly fixed in #47.
