### ISSUE TITLE
Factor graph traversals out of the actual Graph data structure

### ISSUE THREAD

**Issue by Ralith** [Ralith/hypermine#73]
`nearby_nodes` and `ensure_nearby` can be implemented purely through the public interface of `Graph`, and therefore in the interest of encapsulation should be. This will pave the way for specializing traversals to suit more specific purposes, as in #49 and #50.

**Comment by danieldeankon** [comment]
I'm interested in working on this one. I'll have time to get stuck into it over the weekend.
